apiVersion: v1
kind: Secret
metadata:
  name: product-order-system-secret
type: Opaque
stringData:
  # Using stringData instead of data - Kubernetes will auto-encode to base64
  # mongodb://mongodb-user:27017/userdb
  USER_MONGO_URI: mongodb+srv://TechnophileFirdous:Zuni2058Feb@cluster0.hwth0kg.mongodb.net/userdb?appName=Cluster0
  # mongodb://mongodb-product:27017/productdb
  PRODUCT_MONGO_URI: mongodb+srv://TechnophileFirdous:Zuni2058Feb@cluster0.hwth0kg.mongodb.net/productdb?appName=Cluster0
  # mongodb://mongodb-order:27017/orderdb
  ORDER_MONGO_URI: mongodb+srv://TechnophileFirdous:Zuni2058Feb@cluster0.hwth0kg.mongodb.net/orderdb?appName=Cluster0
